# Generated by Django 3.1.7 on 2021-05-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='value',
            new_name='hodnota_atributu_id',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='nazev_atributu_id',
        ),
        migrations.RenameField(
            model_name='attributename',
            old_name='code',
            new_name='kod',
        ),
        migrations.RenameField(
            model_name='attributename',
            old_name='name',
            new_name='nazev',
        ),
        migrations.RenameField(
            model_name='attributename',
            old_name='show',
            new_name='zobrazit',
        ),
        migrations.RenameField(
            model_name='attributevalue',
            old_name='value',
            new_name='hodnota',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='attrs',
            new_name='attributes_ids',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='name',
            new_name='nazev',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='img',
            new_name='obrazek_id',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='products',
            new_name='products_ids',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='link',
            new_name='obrazek',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cena',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='currency',
            new_name='mena',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nazev',
        ),
        migrations.RenameField(
            model_name='productattributes',
            old_name='attr',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='name',
            new_name='nazev',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='img',
            new_name='obrazek_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attrs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
    ]
